language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

install:
  - pip install codecov
  - pip install -r requirements-dev.txt
  - python setup.py develop

script:
  - python -m pytest

after_success:
  - codecov

jobs:
  include:

    - name: "Formatting"
      python: 3.8
      install:
        - pip install black==19.10b0
      script: black --diff --check tvdb_api.py tests/*.py
      after_success: ignore

    - name: "Linting"
      python: 3.8
      install:
        - pip install -r requirements-dev.txt
      script: flake8
      after_success: ignore
