language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

script:
  # pytest==4.6 fallback for Python 2.7
  - pip install pytest==5.4 || pip install pytest==4.6
  - python setup.py develop
  - python -m pytest
